# Generated by Django 3.2.7 on 2021-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_pending_db1'),
    ]

    operations = [
        migrations.CreateModel(
            name='pending_db2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=30)),
                ('dob', models.DateField()),
                ('id_no', models.TextField(max_length=15)),
                ('address', models.TextField(max_length=1000)),
                ('gender', models.TextField(max_length=10, null=True)),
                ('course', models.TextField(max_length=50)),
                ('department', models.TextField(max_length=50)),
                ('specialization', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
                ('notes', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
